#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Jun 16 13:48:38 2021

@author: jake
"""

#%% imports
import pandas as pd
import numpy as np
import umouse.UMousePlotter_functions as UMPlot

#%matplotlib

#%% load Warren data embeddings

df_a = pd.read_csv('201217_000_behavior_df_umap.csv', index_col=0)
df_b = pd.read_csv('201115_000_behavior_df_umap.csv', index_col=0)
df_c = pd.read_csv('201229_000_behavior_df_umap.csv', index_col=0)

UMAP_dfs = [df_a, df_b, df_c]

#generate beahvior labels and legend
bx_df_a = pd.read_csv('201217_000_behavior_df')
bx_df_b = pd.read_csv('201115_000_behavior_df')
bx_df_c = pd.read_csv('201229_000_behavior_df')

bx_dfs = [bx_df_a, bx_df_b, bx_df_c]

# generate random behavior labels
behavior_legend = ['other', 'reward', 'obstacle']
behavior_labels = []
for expt in [bx_df_a, bx_df_b, bx_df_c]:
    expt_labels = np.zeros(len(expt), dtype=int)
    expt_labels[np.where(expt['rewardBool'])] = 1
    expt_labels[np.where(expt['obstacleBool'])] = 2
    behavior_labels.append(expt_labels)


#%% Warren data - interactive

# n: number of clusters, k: number of neighbors in cluster
n = 3
k = 3
spread = 250
fps = 250
ds = 25
video_path = ''  # needs to be hdf5
save_path = 'montage.avi'

# interactive
inter = UMPlot.interactive(n, k, spread, UMAP_dfs, behavior_labels, behavior_legend, ds=25)
# get points
inter.get_points() #save_embedding=True, save_chosen_points=True
# plot traces 
inter.plot_traces(bx_dfs, behavior_variable=['FLX', 'FLY', 'FLZ']) #save=True
# make montage
#inter.behavior_montage(video_path, save_path, fps)

#%% 
#try with one vs multiple datasets
UMPlot.plot_embedding_behavior_labels(UMAP_dfs, behavior_labels, behavior_legend, ds=25, save=False)


#%% 
#try without behavior inputs
UMPlot.plot_embedding(UMAP_dfs, ds=25, sep_data=True, save=False)

#try one vs multi datasets
UMPlot.plot_embedding(UMAP_dfs[0], ds=25, save=False)

#try with behavior inputs
UMPlot.plot_embedding(UMAP_dfs, behavior_labels = behavior_labels, behavior_legend = behavior_legend, ds=25, sep_data=True, save=False)

#try with saving data






